#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import joblib
import pandas as pd
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error, r2_score


def evaluate_direction(model_payload: dict, data_path: Path) -> None:
    frame = pd.read_csv(data_path, parse_dates=["date"])
    features = model_payload["features"]
    model = model_payload["model"]

    predictions = model.predict(frame[features])
    accuracy = accuracy_score(frame["target_up"], predictions)

    print("=== Direction Model ===")
    print(f"Saved model family: {model_payload.get('selected_model')}")
    if "evaluation" in model_payload:
        evaluation = model_payload["evaluation"]
        print("Stored out-of-sample metrics:")
        print(f"  accuracy:          {evaluation['accuracy']:.4f}")
        print(f"  balanced_accuracy: {evaluation['balanced_accuracy']:.4f}")
        print(f"  roc_auc:           {evaluation['roc_auc']:.4f}")
    print(f"In-sample accuracy on full labeled data: {accuracy:.4f}")


def evaluate_return(model_payload: dict, data_path: Path) -> None:
    frame = pd.read_csv(data_path, parse_dates=["date"])
    features = model_payload["features"]
    model = model_payload["model"]

    predictions = model.predict(frame[features])
    mae = mean_absolute_error(frame["next_return"], predictions)
    rmse = mean_squared_error(frame["next_return"], predictions) ** 0.5
    r2 = r2_score(frame["next_return"], predictions)

    print("\n=== Return Model ===")
    print(f"Saved model family: {model_payload.get('selected_model')}")
    if "evaluation" in model_payload:
        evaluation = model_payload["evaluation"]
        print("Stored out-of-sample metrics:")
        print(f"  mae:  {evaluation['mae']:.4f}")
        print(f"  rmse: {evaluation['rmse']:.4f}")
        print(f"  r2:   {evaluation['r2']:.4f}")
    print(f"In-sample MAE on full labeled data: {mae:.4f}")
    print(f"In-sample RMSE on full labeled data: {rmse:.4f}")
    print(f"In-sample R2 on full labeled data: {r2:.4f}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate the saved Easpring stock/news models.")
    parser.add_argument(
        "--direction-model",
        type=Path,
        default=Path("models/direction_model.joblib"),
        help="Path to the saved classification model payload.",
    )
    parser.add_argument(
        "--return-model",
        type=Path,
        default=Path("models/return_model.joblib"),
        help="Path to the saved regression model payload.",
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=Path("data/processed/training_data.csv"),
        help="Path to training_data.csv generated by the pipeline.",
    )
    args = parser.parse_args()

    if not args.data.exists():
        print(f"Missing dataset: {args.data}")
        return 1
    if not args.direction_model.exists():
        print(f"Missing direction model: {args.direction_model}")
        return 1
    if not args.return_model.exists():
        print(f"Missing return model: {args.return_model}")
        return 1

    evaluate_direction(joblib.load(args.direction_model), args.data)
    evaluate_return(joblib.load(args.return_model), args.data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
